export const testKeys = {
  privateKey: `-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACAK85ObhOqmngSLYQ5OAyjyPZfbGxgIZKD2bfo8Hqj0jwAAAKCtPu3crT7t
3AAAAAtzc2gtZWQyNTUxOQAAACAK85ObhOqmngSLYQ5OAyjyPZfbGxgIZKD2bfo8Hqj0jw
AAAEDuolSjLXfVfugWJohlNiRgAp5k6NO2PDzuupcHJP9hJQrzk5uE6qaeBIthDk4DKPI9
l9sbGAhkoPZt+jweqPSPAAAAGmRmb3JzYmVyQE1hY0Jvb2stUHJvLmxvY2FsAQID
-----END OPENSSH PRIVATE KEY-----`,
  publicKey: `ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIArzk5uE6qaeBIthDk4DKPI9l9sbGAhkoPZt+jweqPSP dforsber@MacBook-Pro.local`,
};
