module.exports = {
  testKeys: {
    privateKey: `-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACAIM1AphBWj5UXATeDFi9pUmj1FU2bvI0SdWaiIrVyx7AAAAJjh2YVl4dmF
ZQAAAAtzc2gtZWQyNTUxOQAAACAIM1AphBWj5UXATeDFi9pUmj1FU2bvI0SdWaiIrVyx7A
AAAEBa7w1A49MzJIpGX8r+wUmIBCORS1D6yiPe7J8Rkvf5hAgzUCmEFaPlRcBN4MWL2lSa
PUVTZu8jRJ1ZqIitXLHsAAAAEHRlc3RAZXhhbXBsZS5jb20BAgMEBQ==
-----END OPENSSH PRIVATE KEY-----`,
    publicKey: `ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAgzUCmEFaPlRcBN4MWL2lSaPUVTZu8jRJ1ZqIitXLHs test@example.com`
  }
};
